name: sgf_parser
description: Parser library for SGF (Smart Game Format) files. Currently only supports Go.
version: 0.0.3
author: Umut Seven <umutseven92@gmail.com>
homepage: https://umutseven.com

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: